apiVersion: apps/v1
kind: Deployment
metadata:
  name: credit-score
  namespace: default
spec:
  replicas: 2
  selector:
    matchLabels:
      app: credit-score
  template:
    metadata:
      labels:
        app: credit-score
    spec:
      containers:
      - name: credit-score
        image: mohammadshp/credit-score:latest
        ports:
        - containerPort: 8000
        readinessProbe:
          httpGet:
            path: /docs
            port: 8000
          initialDelaySeconds: 15
          periodSeconds: 10
